### ISSUE TITLE
Extract the required GDP data 

### ISSUE THREAD

**Issue by Carl0sGutierrez** [Carl0sGutierrez/GDP-Data-extraction-and-processing#1]
Estimate: 1 day 

## Tasks

- [x] Extract tables from webpage using Pandas. 
- [x] Retain table number 3 as the required dataframe.
- [x] Replace the column headers with column numbers.
- [x] Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
- [x] Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
- [x] Assign column names as "Country" and "GDP (Million USD)".
- [x] Unit test

## Resources 

- [URL](https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29)

**Note:** To extract the required table directly as a Dataframe. The required table is the thrid one on the website, as shown in the image bellow.

![Screenshot 2024-11-05 at 23 54 29](https://github.com/user-attachments/assets/765816ee-a099-4640-8512-f101465dadb4)
